version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "@hcengineering/*"
    groups:
      hcengineering:
        patterns:
          - "@hcengineering/*"
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "effect"
      - dependency-name: "@effect/*"
    groups:
      effect:
        patterns:
          - "effect"
          - "@effect/*"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
